# Generated by Django 6.0.3 on 2026-03-05 15:27

import TailTales.care.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2, message='Appointment title must be at least 2 characters long.')])),
                ('date', models.DateField(validators=[TailTales.care.validators.validate_future_or_today_date])),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='pets.pet')),
                ('service_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='contacts.servicecontact')),
            ],
        ),
        migrations.CreateModel(
            name='PreventiveCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_type', models.CharField(choices=[('Flea and Tick', 'Flea and Tick'), ('Deworming', 'Deworming'), ('Heartworm', 'Heartworm'), ('Other', 'Other')], max_length=20)),
                ('product_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2, message='Product name must be at least 2 characters long.')])),
                ('last_given_date', models.DateField(validators=[TailTales.care.validators.validate_today_or_past_date])),
                ('next_due_date', models.DateField(validators=[TailTales.care.validators.validate_future_or_today_date])),
                ('notes', models.TextField(blank=True, null=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preventive_care_items', to='pets.pet')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('pet', 'care_type'), name='unique_preventive_care_type_per_pet')],
            },
        ),
    ]
