# Generated by Django 6.0.3 on 2026-03-08 15:45

import TailTales.care.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventivecare',
            name='interval_days',
            field=models.PositiveIntegerField(choices=[(30, 'Monthly (30 days)'), (90, 'Every 3 months'), (180, 'Every 6 months'), (365, 'Yearly')], default=30, help_text='How often this treatment should repeat.'),
        ),
        migrations.AlterField(
            model_name='preventivecare',
            name='care_type',
            field=models.CharField(choices=[('flea_tick', 'Flea & Tick'), ('deworming', 'Deworming'), ('heartworm', 'Heartworm'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='preventivecare',
            name='next_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PreventiveCareDose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_date', models.DateField(validators=[TailTales.care.validators.validate_today_or_past_date])),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preventive_care', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doses', to='care.preventivecare')),
            ],
            options={
                'ordering': ['-given_date'],
            },
        ),
    ]
