# Generated by Django 6.0.3 on 2026-03-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='show_in_gallery',
            field=models.BooleanField(default=True, verbose_name='Show in public gallery'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat')], max_length=20),
        ),
    ]
