# Generated by Django 6.0.3 on 2026-03-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_pet_show_in_gallery_alter_pet_species'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='pet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pets/'),
        ),
    ]
