# Generated by Django 6.0.3 on 2026-03-05 15:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('Vet', 'Vet'), ('Groomer', 'Groomer'), ('Trainer', 'Trainer'), ('Other', 'Other')], max_length=10)),
                ('name', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(2, message='Contact name must be at least 2 characters long.')])),
                ('phone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number can contain only digits and an optional + at the beginning.', regex='^\\+?\\d+$')])),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
